#!/usr/bin/env bash
# SPDX-FileCopyrightText: 2026 Rile contributors
# SPDX-License-Identifier: GPL-3.0-or-later

set -euo pipefail

cargo fmt --check
cargo clippy --locked --all-targets --all-features -- -D warnings
