#!/usr/bin/env bash
# SPDX-FileCopyrightText: 2026 Robert Charusta <rch-public@posteo.net>
# SPDX-License-Identifier: GPL-3.0-or-later

set -euo pipefail

"$(dirname -- "$0")/fmt-check"
cargo clippy --locked --all-targets --all-features -- -D warnings
