#!/usr/bin/env bash
# SPDX-FileCopyrightText: 2026 Robert Charusta <rch-public@posteo.net>
# SPDX-License-Identifier: GPL-3.0-or-later

set -euo pipefail

RILE_SNAPSHOT_TEST=1 cargo insta test --check --test pty_snapshots "$@"
